/**
 * build.mjs — compile both frontend (Vite) and server (esbuild) in sequence.
 * Run with: node build.mjs   (called automatically by `npm run build`)
 */
import { execSync } from "child_process";
import { build } from "esbuild";

console.log("▶ Building frontend (Vite)…");
execSync("./node_modules/.bin/vite build", { stdio: "inherit" });

console.log("\n▶ Building server (esbuild)…");
await build({
  entryPoints: ["server.ts"],
  bundle: true,
  platform: "node",
  format: "esm",
  outfile: "dist/server.mjs",
  // keep node_modules external — they are resolved at runtime from the project root
  packages: "external",
  banner: { js: "// Ka Education Server — generated by esbuild\n" },
});

console.log("\n✓ Build complete.");
console.log("  Start:  npm start");
console.log("  Port:   PORT env var (default 3000)");
